# Generated by Django 6.0 on 2026-10-05 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_customuser_is_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='CityruleMaster',
            fields=[
                ('ruleId', models.AutoField(primary_key=True, serialize=False)),
                ('citytype', models.CharField(max_length=20)),
                ('rule_number', models.IntegerField()),
                ('day_number', models.CharField(blank=True, max_length=70)),
                ('time_in_hours', models.FloatField(blank=True, null=True)),
                ('virgin_plastic_price', models.FloatField(blank=True, null=True)),
                ('recycled_plastic_price', models.FloatField(blank=True, null=True)),
                ('envtx_p_shampoo', models.FloatField(blank=True, null=True)),
                ('envtx_p_bvb', models.FloatField(blank=True, null=True)),
                ('envtx_p_brcb', models.FloatField(blank=True, null=True)),
                ('envtx_p_brfb', models.FloatField(blank=True, null=True)),
                ('envtx_p_uvb', models.FloatField(blank=True, null=True)),
                ('envtx_p_urcb', models.FloatField(blank=True, null=True)),
                ('envtx_p_urfb', models.FloatField(blank=True, null=True)),
                ('envtx_r_bvb', models.FloatField(blank=True, null=True)),
                ('envtx_r_brcb', models.FloatField(blank=True, null=True)),
                ('envtx_r_brfb', models.FloatField(blank=True, null=True)),
                ('envtx_r_uvb', models.FloatField(blank=True, null=True)),
                ('envtx_r_urcb', models.FloatField(blank=True, null=True)),
                ('envtx_r_urfb', models.FloatField(blank=True, null=True)),
                ('envtx_c_bvb', models.FloatField(blank=True, null=True)),
                ('envtx_c_brcb', models.FloatField(blank=True, null=True)),
                ('envtx_c_brfb', models.FloatField(blank=True, null=True)),
                ('envtx_c_uvb', models.FloatField(blank=True, null=True)),
                ('envtx_c_urcb', models.FloatField(blank=True, null=True)),
                ('envtx_c_urfb', models.FloatField(blank=True, null=True)),
                ('fine_for_throwing_bottle', models.FloatField(blank=True, null=True)),
                ('dustbinning_fine', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'CityruleMaster',
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='customuser',
            name='email_verification_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='email_verification_token',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
