"""
Django settings for shorterloops project.

Generated by 'django-admin startproject' using Django 4.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""
import os
from datetime import timedelta

from pathlib import Path
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure--661w!od8dop7h2eaox6qodw1^bnl_pyk@#tsro)sc-b-&6vs@'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

load_dotenv()
# Application definition

INSTALLED_APPS = [
    'daphne',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'crispy_forms',
    'accounts',
    'rest_framework',
    'corsheaders',
    'bootstrap4',
    'auditlog',
 #   'silk',
    'channels',

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
  #  'silk.middleware.SilkyMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'auditlog.middleware.AuditlogMiddleware',
]

ROOT_URLCONF = 'shorterloops.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]
CRISPY_TEMPLATE_PACK = 'bootstrap4'
WSGI_APPLICATION = 'shorterloops.wsgi.application'
ASGI_APPLICATION = "shorterloops.asgi.application"


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases
# {
#     'ENGINE': 'django.db.backends.mysql',
#     'NAME': 'fresh',
#     'USER': 'root',
#     'PASSWORD': 'Admin@123',
#     'HOST': '127.0.0.1',
#     'PORT': '3306',
# }
DATABASES = {

    'default':
        {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': 'shorterloop',
            'USER': 'shorterloops',
            'PASSWORD': 'Admin@1234',
            'HOST': '127.0.0.1',
            'PORT': '3306',
        }
    # {
    #     'ENGINE': 'django.db.backends.mysql',
    #     'OPTIONS': {
    #         'sql_mode': 'traditional',
    #     },
    #     'NAME': 'shorterloop',
    #     'USER': 'dbluser',
    #     'PASSWORD': 'Dbladmin@123',
    #     'HOST': '127.0.0.1',
    #     'PORT': '3306',
    # }
}

# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

# STATICFILES_DIRS = (
#     os.path.join(BASE_DIR, "static"),
# )

STATIC_URL = '/static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
CRISPY_TEMPLATE_PACK = 'bootstrap4'
LOGIN_REDIRECT_URL = '/'
CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True
# CORS_REPLACE_HTTPS_REFERER = True
CORS_ALLOWED_ORIGINS = [
    "http://localhost:4200",
    "http://127.0.0.1:4200"
]

# CSRF_TRUSTED_ORIGINS = [
#     'https://dbl.iihs.in',
#     'https://10.10.4.129',
# ]

# CORS_ORIGIN_WHITELIST = (
#     'https://dbl.iihs.in',
#     'https://10.10.4.129',
# )
CORS_ORIGIN_ALLOW_ALL = False

CORS_ALLOW_HEADERS = [
    'Content-Type',
    'Authorization',
    'user-data',  # Add 'user-data' to the list of allowed headers
]

CORS_ORIGIN_WHITELIST = [
    'http://localhost:4200',  # Add the origin of your Angular application
]
REST_FRAMEWORK = {
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
    ],
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    )
}
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
        },
    },
    'loggers': {
        'auditlog': {
            'handlers': ['console'],
            'level': 'DEBUG',
        },
    },
}
AUTH_USER_MODEL = 'accounts.CustomUser'
# settings.py
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'accounts.backends.CustomUserAuthBackend',  # Your custom backend
]

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'USER_ID_FIELD': 'UserId',
    'USER_ID_CLAIM': 'user_id',
}


CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [
                {
                    "address": "redis://127.0.0.1:6379/0",
                    "socket_timeout": 30,
                    "socket_connect_timeout": 5,
                }
            ],
        },
    },
}

CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.redis.RedisCache",
        "LOCATION": "redis://127.0.0.1:6379/1",
    }
}



EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.zeptomail.in'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD")
DEFAULT_FROM_EMAIL = '"Shorterloops" <shorterloops.dbl@iihs.ac.in>'
SERVER_EMAIL = 'shorterloops.dbl@iihs.ac.in'
# EMAIL_DEBUG = True

ACCOUNT_EMAIL_SUBJECT_PREFIX = 'Shorterloops - '
ACCOUNT_EMAIL_VERIFICATION_SUBJECT = 'Verify your email address'
ACCOUNT_EMAIL_CONFIRMATION_EXPIRE_DAYS = 1