from django.contrib import admin
from accounts.views import SignUpView, LoginView, UserProfileView, UserListView
from django.urls import include, path
from accounts import views
from rest_framework_simplejwt.views import TokenRefreshView
urlpatterns = [
    path("admin/", admin.site.urls),
    path('api/api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    path('api/users/', UserListView.as_view(), name='user-list'),
    path('api/auth/signup/', SignUpView.as_view(), name='signup'),
    path('api/auth/login/', LoginView.as_view(), name='login'),
    path('auth/refresh/', TokenRefreshView.as_view()),
    path('api/auth/profile/', UserProfileView.as_view(), name='profile'),
    path('api/updateusercity/<userid>',
         views.updateusercity, name='updateusercity'),
    # path('api/signup/', views.signup, name='signup'),
    path('api/addcity/', views.addcity, name='addcity'),
    path('api/addcity/<cityid>', views.editcity, name='editcity'),
    path('api/get-csrf/', views.get_csrf, name='get_csrf'),
    path('api/updatetime/<cityid>', views.updatecurrent, name='updatecurrent'),
    path('api/getcityname/<cityid>', views.getcityname, name='getcityname'),
    path('api/facility/<mayorid>', views.facility, name='facility'),
    path('api/getfacility/<cityid>', views.getfacility, name='getfacility'),
    path('api/updatefacility/', views.updatefacility, name='updatefacility'),
    path('api/leavefacility/<userid>', views.leavefacility, name='leavefacility'),
    path('api/asset/<cityid>', views.createasset, name='createasset'),
    path('api/assets/<itemid>', views.returnasset, name='returnasset'),
    path('api/lockasset/<itemid>', views.lockasset, name='lockasset'),
    path('api/unlockasset/<itemid>', views.unlockasset, name='unlockasset'),
    path('api/update_city_threads/', views.update_city_threads,
         name='update_city_threads'),
    # path('api/receive_user_details/', views.receive_user_data, name='receive_user_data'),
    path('api/cashflow/', views.createtransaction, name='createtransaction'),
    path('api/cashflow/<str:cityid>/<username>', views.getParticulartransaction,
         name='getParticulartransaction'),
    path('api/audit-log/<asset_id>/', views.get_audit_logs, name='get_audit_logs'),
    path('api/audit-logs/<user>/', views.get_audit_logsuser,
         name='get_audit_logsuser'),
    path('api/bottleprice/', views.get_BottlePrice, name='get_BottlePrice'),
    path('api/shampooprice/', views.get_ShampooPrice, name='get_ShampooPrice'),
    path('api/updatetransactionfacility/<cityid>',
         views.updatetransactionfacility, name='updatetransactionfacility'),
    path('api/getFacilityCashbox/<str:facilityName>/<cityid>',
         views.getfacilitycash, name='getfacilitycash'),
    path('api/filter-audit-logs/', views.filter_audit_logs,
         name='filter_audit_logs'),
    path('api/filter-options/', views.get_filter_options,
         name='get_filter_options'),
    path('api/addRule/', views.add_Cityrule, name='add_Cityrule'),
    path('api/inventory/', views.bottle_inventory_detail, name='bottle_inventory_detail'),
    path("api/toggle-timer/<cityid>",
         views.toggle_city_timer, name="toggle_city_timer"),
    path('api/cityrule/<city_id>', views.get_last_city_rule,
         name='get_last_city_rule'),
    path("api/reservebottle/<str:itemid>/",views.reserve_bottle,),
    path('api/purchase/', views.purchase, name='purchase'),
    path('api/calculatepurchase/', views.calculatepurchase, name='calculatepurchase'),
    
    path('api/returnbottle/',views.return_bottle,name='return_bottle'),
    path('silk/', include('silk.urls', namespace='silk')),
    
   # path('api/get_last_serial/', views.get_last_serial, name='get_last_serial'),


]
